- name: daemon reload
  command: systemctl daemon-reload

- name: start flanneld
  systemd:
    daemon_reload: yes
    name: flanneld
    enabled: yes
    state: started

- name: restart flanneld
  systemd:
    daemon_reload: yes
    name: flanneld
    state: restarted

- name: restart kubelet
  systemd:
    daemon_reload: yes
    name: kubelet
    state: restarted

- name: restart etcd2
  systemd:
    daemon_reload: yes
    name: etcd2
    state: restarted
